package alphacalculator.gui;

/**
 * @author Wanga Knajala
 */

import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        jTextField_calculation.setText("0");
    }
    double storedNumber;
    private String currentOperation = "";


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_textField = new javax.swing.JPanel();
        jTextField_calculation = new javax.swing.JTextField();
        jPanel_buttons = new javax.swing.JPanel();
        jButton_pi = new javax.swing.JButton();
        jButton_percentage = new javax.swing.JButton();
        jButton_del = new javax.swing.JButton();
        jButton_division = new javax.swing.JButton();
        jButton_7 = new javax.swing.JButton();
        jButton_8 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_multiplication = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_subtraction = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_1 = new javax.swing.JButton();
        jButton_addition = new javax.swing.JButton();
        jButton_point = new javax.swing.JButton();
        jButton_0 = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jButton_equals = new javax.swing.JButton();
        jLabel_calculation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Calculator");
        setPreferredSize(new java.awt.Dimension(315, 410));
        setResizable(false);

        jPanel_textField.setLayout(new java.awt.GridLayout(1, 0));

        jTextField_calculation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_calculation.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel_textField.add(jTextField_calculation);

        jButton_pi.setText("π");
        jButton_pi.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_pi.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_pi.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_piActionPerformed(evt);
            }
        });

        jButton_percentage.setText("%");
        jButton_percentage.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_percentage.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_percentage.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_percentageActionPerformed(evt);
            }
        });

        jButton_del.setText("Del");
        jButton_del.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_del.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_del.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delActionPerformed(evt);
            }
        });

        jButton_division.setText("÷");
        jButton_division.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_division.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_division.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_divisionActionPerformed(evt);
            }
        });

        jButton_7.setText("7");
        jButton_7.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_7.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_7.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7ActionPerformed(evt);
            }
        });

        jButton_8.setText("8");
        jButton_8.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_8.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_8.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_8ActionPerformed(evt);
            }
        });

        jButton_9.setText("9");
        jButton_9.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_9.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_9.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_9ActionPerformed(evt);
            }
        });

        jButton_multiplication.setText("x");
        jButton_multiplication.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_multiplication.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_multiplication.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_multiplicationActionPerformed(evt);
            }
        });

        jButton_4.setText("4");
        jButton_4.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_4.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_4.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4ActionPerformed(evt);
            }
        });

        jButton_5.setText("5");
        jButton_5.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_5.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_5.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5ActionPerformed(evt);
            }
        });

        jButton_6.setText("6");
        jButton_6.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_6.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_6.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6ActionPerformed(evt);
            }
        });

        jButton_subtraction.setText("-");
        jButton_subtraction.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_subtraction.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_subtraction.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_subtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_subtractionActionPerformed(evt);
            }
        });

        jButton_3.setText("3");
        jButton_3.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_3.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_3.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3ActionPerformed(evt);
            }
        });

        jButton_2.setText("2");
        jButton_2.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_2.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_2.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2ActionPerformed(evt);
            }
        });

        jButton_1.setText("1");
        jButton_1.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_1.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });

        jButton_addition.setText("+");
        jButton_addition.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_addition.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_addition.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_additionActionPerformed(evt);
            }
        });

        jButton_point.setText(".");
        jButton_point.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_point.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_point.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pointActionPerformed(evt);
            }
        });

        jButton_0.setText("0");
        jButton_0.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_0.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_0.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_0ActionPerformed(evt);
            }
        });

        jButton_clear.setText("CE");
        jButton_clear.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_clear.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_clear.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jButton_equals.setText("=");
        jButton_equals.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton_equals.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton_equals.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_equalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_buttonsLayout = new javax.swing.GroupLayout(jPanel_buttons);
        jPanel_buttons.setLayout(jPanel_buttonsLayout);
        jPanel_buttonsLayout.setHorizontalGroup(
            jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                        .addComponent(jButton_pi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_del, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_division, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                        .addComponent(jButton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_multiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                        .addComponent(jButton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_subtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                        .addComponent(jButton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_addition, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                        .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                                .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_point, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_calculation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_equals, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_buttonsLayout.setVerticalGroup(
            jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_del, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_pi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_division, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_multiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_subtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_addition, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_point, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_equals, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_calculation, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_textField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    // when user clicks the number zero
    private void jButton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_0ActionPerformed
        // if the value started at zero
        if(jTextField_calculation.getText().equals("0")){
            // empty textfield 
            jTextField_calculation.setText("");
        }
        // append the number zero
        jTextField_calculation.setText(jTextField_calculation.getText() + Integer.toString(0));
    }//GEN-LAST:event_jButton_0ActionPerformed

    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
        // if the value started at zero
        if(jTextField_calculation.getText().equals("0")){
            // empty textfield 
            jTextField_calculation.setText("");
        }
        // append the number one
        jTextField_calculation.setText(jTextField_calculation.getText() + Integer.toString(1));
    }//GEN-LAST:event_jButton_1ActionPerformed

    private void jButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2ActionPerformed
        // if the value started at one
        if(jTextField_calculation.getText().equals("0")){
            // empty textfield 
            jTextField_calculation.setText("");
        }
        // append the number one
        jTextField_calculation.setText(jTextField_calculation.getText() + Integer.toString(2));
    }//GEN-LAST:event_jButton_2ActionPerformed

    private void jButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3ActionPerformed
        // if the value started at one
        if(jTextField_calculation.getText().equals("0")){
            // empty textfield 
            jTextField_calculation.setText("");
        }
        // append the number one
        jTextField_calculation.setText(jTextField_calculation.getText() + Integer.toString(3));
    }//GEN-LAST:event_jButton_3ActionPerformed

    private void jButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4ActionPerformed
        // if the value started at one
        if(jTextField_calculation.getText().equals("0")){
            // empty textfield 
            jTextField_calculation.setText("");
        }
        // append the number one
        jTextField_calculation.setText(jTextField_calculation.getText() + Integer.toString(4));
    }//GEN-LAST:event_jButton_4ActionPerformed

    private void jButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5ActionPerformed
        // if the value started at one
        if(jTextField_calculation.getText().equals("0")){
            // empty textfield 
            jTextField_calculation.setText("");
        }
        // append the number one
        jTextField_calculation.setText(jTextField_calculation.getText() + Integer.toString(5));
    }//GEN-LAST:event_jButton_5ActionPerformed

    private void jButton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6ActionPerformed
        // if the value started at one
        if(jTextField_calculation.getText().equals("0")){
            // empty textfield 
            jTextField_calculation.setText("");
        }
        // append the number one
        jTextField_calculation.setText(jTextField_calculation.getText() + Integer.toString(6));
    }//GEN-LAST:event_jButton_6ActionPerformed

    private void jButton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7ActionPerformed
        // if the value started at one
        if(jTextField_calculation.getText().equals("0")){
            // empty textfield 
            jTextField_calculation.setText("");
        }
        // append the number one
        jTextField_calculation.setText(jTextField_calculation.getText() + Integer.toString(7));
    }//GEN-LAST:event_jButton_7ActionPerformed

    private void jButton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_8ActionPerformed
        // if the value started at one
        if(jTextField_calculation.getText().equals("0")){
            // empty textfield 
            jTextField_calculation.setText("");
        }
        // append the number one
        jTextField_calculation.setText(jTextField_calculation.getText() + Integer.toString(8));
    }//GEN-LAST:event_jButton_8ActionPerformed

    private void jButton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_9ActionPerformed
        // if the value started at one
        if(jTextField_calculation.getText().equals("0")){
            // empty textfield 
            jTextField_calculation.setText("");
        }
        // append the number one
        jTextField_calculation.setText(jTextField_calculation.getText() + Integer.toString(9));
    }//GEN-LAST:event_jButton_9ActionPerformed

    private void jButton_additionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_additionActionPerformed
        // Get the current text from the text field
        String currentText = jTextField_calculation.getText();

        // Check if the text is not empty
        if (!currentText.isEmpty()) {
            // Convert the text to a double
            double currentNumber = Double.parseDouble(currentText);

            // Store the current number in a variable
            storedNumber = currentNumber;

            // Clear the text field for the next input
            jTextField_calculation.setText("");
            
            // Tell the user what they are doing
            jLabel_calculation.setText(currentText + " add by...");

            // Set the current operation to addition
            currentOperation = "addition";
        }
    }//GEN-LAST:event_jButton_additionActionPerformed

    private void jButton_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_equalsActionPerformed
        // Get the current text from the text field
        String currentText = jTextField_calculation.getText();
        
        // Check if the text is not empty
        if (!currentText.isEmpty()) {
            // Convert the text to a double
            double currentNumber = Double.parseDouble(currentText);

            // Perform the operation based on the currentOperation
            switch (currentOperation) {
                case "addition":
                    double resultAddition = storedNumber + currentNumber;
                    jTextField_calculation.setText(Double.toString(resultAddition));
                    break;
                case "subtraction":
                    double resultSubtraction = storedNumber - currentNumber;
                    jTextField_calculation.setText(Double.toString(resultSubtraction));
                    break;
                case "multiplication":
                    double resultMultiplication = storedNumber * currentNumber;
                    jTextField_calculation.setText(Double.toString(resultMultiplication));
                    break;
                case "division":
                    try {
                        // Attempt to perform division
                        double resultDivision = storedNumber / currentNumber;

                        // Check for special cases like division by zero
                        if (Double.isInfinite(resultDivision) || Double.isNaN(resultDivision)) {
                            throw new ArithmeticException("Invalid division");
                        }

                        // Update the text field with the result
                        jTextField_calculation.setText(Double.toString(resultDivision));
                    } catch (ArithmeticException e) {
                        // Handle division by zero or other arithmetic errors
                        jTextField_calculation.setText("Error");
                    }
                    break;
                default:
                    // Handle the default case (no valid operation)
                    break;
            }
        
        // Reset the current operation and stored number
        currentOperation = "";
        storedNumber = 0.0; // Reset to the default value
        // Tell the user what they are doing
            jLabel_calculation.setText("");
        }
    }//GEN-LAST:event_jButton_equalsActionPerformed

    private void jButton_subtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_subtractionActionPerformed
        // Get the current text from the text field
        String currentText = jTextField_calculation.getText();

        // Check if the text is not empty
        if (!currentText.isEmpty()) {
            // Convert the text to a double
            double currentNumber = Double.parseDouble(currentText);

            // Store the current number in a variable
            storedNumber = currentNumber;

            // Clear the text field for the next input
            jTextField_calculation.setText("");
            
            // Tell the user what they are doing
            jLabel_calculation.setText(currentText + " subtract by...");

            // Set the current operation to subtraction
            currentOperation = "subtraction";
        }
    }//GEN-LAST:event_jButton_subtractionActionPerformed

    private void jButton_multiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_multiplicationActionPerformed
        // Get the current text from the text field
        String currentText = jTextField_calculation.getText();

        // Check if the text is not empty
        if (!currentText.isEmpty()) {
            // Convert the text to a double
            double currentNumber = Double.parseDouble(currentText);

            // Store the current number in a variable
            storedNumber = currentNumber;

            // Clear the text field for the next input
            jTextField_calculation.setText("");
            
            // Tell the user what they are doing
            jLabel_calculation.setText(currentText + " multiplied by...");

            // Set the current operation to subtraction
            currentOperation = "multiplication";
        }
    }//GEN-LAST:event_jButton_multiplicationActionPerformed

    private void jButton_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_divisionActionPerformed
        // Get the current text from the text field
        String currentText = jTextField_calculation.getText();

        // Check if the text is not empty
        if (!currentText.isEmpty()) {
            // Convert the text to a double
            double currentNumber = Double.parseDouble(currentText);

            // Store the current number in a variable
            storedNumber = currentNumber;

            // Clear the text field for the next input
            jTextField_calculation.setText("");
            
            // Tell the user what they are doing
            jLabel_calculation.setText(currentText + " divided by...");

            // Set the current operation to subtraction
            currentOperation = "division";
        }
    }//GEN-LAST:event_jButton_divisionActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        // Clear the text field for the next input
        jTextField_calculation.setText("0");
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delActionPerformed
        // Get the current text from the text field
        String currentText = jTextField_calculation.getText();

        // Check if the text is not empty
        if (!currentText.isEmpty()) {
            // Remove the last character
            String newText = currentText.substring(0, currentText.length() - 1);

            // Update the text field with the new text
            jTextField_calculation.setText(newText);
        }
    }//GEN-LAST:event_jButton_delActionPerformed

    private void jButton_piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_piActionPerformed
        // Get the current text from the text field
        String currentText = jTextField_calculation.getText();

        // Check if the text is not empty
        if (!currentText.isEmpty()) {
            // Convert the text to a double
            double currentNumber = Double.parseDouble(currentText);

            // Calculate the Pi
            double resultPercentage = currentNumber * 3.1415926536;

            // Update the text field with the result
            jTextField_calculation.setText(Double.toString(resultPercentage));

            // Reset the current operation and stored number
            currentOperation = "";
            storedNumber = 0.0; // Reset to the default value
        }
    }//GEN-LAST:event_jButton_piActionPerformed

    private void jButton_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_percentageActionPerformed
        // Get the current text from the text field
        String currentText = jTextField_calculation.getText();

        // Check if the text is not empty
        if (!currentText.isEmpty()) {
            // Convert the text to a double
            double currentNumber = Double.parseDouble(currentText);

            // Calculate the percentage
            double resultPercentage = currentNumber / 100.0;

            // Update the text field with the result
            jTextField_calculation.setText(Double.toString(resultPercentage));

            // Reset the current operation and stored number
            currentOperation = "";
            storedNumber = 0.0; // Reset to the default value
        }
    }//GEN-LAST:event_jButton_percentageActionPerformed

    private void jButton_pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pointActionPerformed
        // if the value started at zero
        if(jTextField_calculation.getText().equals("0")){
            // empty textfield 
            jTextField_calculation.setText("");
        }
        // append the number one
        jTextField_calculation.setText(jTextField_calculation.getText() + ".");
    }//GEN-LAST:event_jButton_pointActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_0;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JButton jButton_addition;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_del;
    private javax.swing.JButton jButton_division;
    private javax.swing.JButton jButton_equals;
    private javax.swing.JButton jButton_multiplication;
    private javax.swing.JButton jButton_percentage;
    private javax.swing.JButton jButton_pi;
    private javax.swing.JButton jButton_point;
    private javax.swing.JButton jButton_subtraction;
    private javax.swing.JLabel jLabel_calculation;
    private javax.swing.JPanel jPanel_buttons;
    private javax.swing.JPanel jPanel_textField;
    private javax.swing.JTextField jTextField_calculation;
    // End of variables declaration//GEN-END:variables
}
